class AppStrings {
  static final Map<String, String> _englishStrings = {
    'title': 'मेरा ऐप',
    'welcome_message': 'मेरे ऐप में आपका स्वागत है!',
    'next': 'क्लिक करें',
    "please_enter_four_digit_otp": "कृपया चार अंकों का ओटीपी दर्ज करें",
    "enter_confirm_pin_here": "दोबारा पिन दर्ज करें..",
    "enter_pin_here": "पिन दर्ज करें..",
    "please_create_four_digit_pin": "कृपया चार अंकों का पिन बनाएं!",
    "create_pin": "पिन बनाएं",
    "registration_with_mobile_number": "मोबाइल नंबर के साथ पंजीकरण",
    "enter_mobile_number_here": "मोबाइल नंबर दर्ज करें...",
    "enter_password_here": "पासवर्ड दर्ज करें...",
    "login": "लॉग इन करें",
    "inspection": "निरीक्षण करें",
    "report": "निरीक्षण रिपोर्ट देखें",
    "leave": "छुट्टी",
    "samajkalyan_inspection": "समाज कल्याण निरीक्षण",
    "school_inspection": "विद्यालय\nनिरीक्षण",
    "hostel_inspection": "छात्रावास\nनिरीक्षण",
    "vridha_ashram_inspection": "वृद्धाश्रम\nनिरीक्षण",
    "samajkalyan_inspection_report": "समाज कल्याण निरीक्षण रिपोर्ट",
    "school_inspection_report": "विद्यालय निरीक्षण\nरिपोर्ट",
    "hostel_inspection_report": "छात्रावास निरीक्षण\nरिपोर्ट ",
    "vridha_ashram_inspection_report": "वृद्धाश्रम निरीक्षण\nरिपोर्ट",
    "please_enter_correct_pin": "कृपया सही पिन दर्ज करें|",
    "please_wait": "कृपया प्रतीक्षा करें...",
    "master_screen_hint":
        "कृप्या ऐप को ऑफलाइन उपयोग करने के लिए डेटा को डाउनलोड करने तक प्रतीक्षा करें।",
    "database_name": 'Samajkalyan.db',
    "something_went_to_wrong_please_try_again":
        "कुछ ग़लत पाया गया है। कृपाया पुन: प्रयास करें!!",
    "yes": "हाँ",
    "no": "नहीं",

    "inspection_dashBoard": "निरीक्षण",
    "school_name": "विद्यालय का नाम",
    "school_udisecode": "यू-डायस कोड",
    "school_inspection_toolbar": "विद्यालय निरीक्षण",
    "school_inspection_report_toolbar": "निरीक्षण रिपोर्ट",
    "hostel_inspection_toolbar": "छात्रावास निरीक्षण",
    "vridha_ashram_inspection_toolbar": "वृद्धाश्रम निरीक्षण",
    "please_click_only_three_image": "कृपया आप केवल तीन फोटो क्लिक करें|",
    "please_click_three_image": "कृपया तीन फोटो क्लिक करें|",
    "data_not_found": "डेटा नहीं मिला...",
    "image_uploaded_successfully": "आपका फोटो सफलतापूर्वक अपलोड हो गया है|",
    "no_internet_connection": "आपका इंटरनेट कनेक्शन उपलब्ध नहीं है|",
    "please_click_single_image": "कृपया एक फोटो क्लिक करें|",
    "you_school_location_is_pending": "आपकी लोकेशन लंबित है|",
    "you_school_location_is_reject": "आपकी लोकेशन अस्वीकृत है|",
    "enter_here": "यहाँ भरे",
    "regular_in-charge_principal": "नियमित/प्रभारी प्रधानाचार्य",
    "regular_spokesperson": "नियमित प्रवक्ता",
    "contract_spokesperson": "संविदा प्रवक्ता",
    "regular_assistant_teacher": "नियमित सहायक अध्यापक",
    "contract_assistant_teacher": "संविदा सहायक अध्यापक",
    "varist_sahayak": "वरिष्ठ सहायक",
    "kanist_sahayak": "कनिष्ठ सहायक",
    "hostel_assistant": "छात्रवास सहायक",
    "formist": "फार्मासिस्ट",
    "computer_operator": "कंप्यूटर ऑपरेटर",
    "niyamit_chaturath_sherri_karmchari": "नियमित चतुर्थ श्रेणी कर्मचारी",
    "contract_chaturath_sherri_karmchari": "संविदा चतुर्थ श्रेणी कर्मचारी",
    "outsourcing_chaturath_sherri_karmchari":
        "आउटसोर्सिंग चतुर्थ श्रेणी कर्मचारी",
    "surachha_gaurd_home_gaurd_prd": "सुरक्षा गार्ड (होम गार्ड/पी0आर0डी)",
    "regular_cleaning_staff": "नियमित सफाई कर्मचारी",
    "outsourcing_cleaning_staff": "आउटसोर्सिंग सफाई कर्मचारी",
    "total": " कुल",
    "vidayalay_ki_kul_chhatr_chhamta_kitani_hai":
        "विद्यालय की कुल छात्र छमता कितनी है |",
    "vidayalay_me_kul_panjikrit_chhaaatr/chhaatrao_ki_number":
        "विद्यालय में पंजीकृत छात्र/छात्राओं की संख्या",
    "vidayalay_me_kul_upasthit_chhaaatr/chhaatrao_ki_number":
        "विद्यालय में उपस्थित छात्र/छात्राओं की संख्या",
    "vidhayalay_me_karyarat_shaicharick_karmcharyo_ki_number_ke_sambhan":
        "विद्यालय में कार्यरत शैक्षणिक कर्मचारियों की संख्या के संबंध में-",
    "serial_no": "क्रमांक",
    "name_of_staff": "कर्मचारी का नाम",
    "from_date": "दिनांक से",
    "to_date": "दिनांक तक",
    "applied_for_leave": "छुट्टी का अवेदान हुआ",
    "accept": "स्वीकृत",
    "reject": "अस्वीकृत",
    "forward": "प्रेषित करे",
    "type_of_holiday": "छुट्टी का प्रकार",
    "save": "सबमिट करें",
    "mandal_and_district": "मण्डल एवं जिले का चयन करें",
    'data_saved_successfully': "आपका डाटा सफलतापूर्वक सेव हो गया है|",
    "please_select_mandal": "कृपया मण्डल चुनें",
    'please_select_district': "कृपया जिला चुनें",
    "mandal": "मण्डल",
    'district': "जिला",
    'select': "--चुनें--",
    'school_data_saved_successfully':
        'विद्यालय का डाटा सफलतापूर्वक सेव हो गया है|',
    'dashBoard': 'डैशबोर्ड',
    'switchUser': 'यूजर बदलें',
    'schoolListUpdate': 'विद्यालय लिस्ट अपडेट करें',
    'questionnairesListUpdate': 'प्रश्नावली अपडेट करें',
    'reportUpdate': 'रिपोर्ट अपडेट करें',
    'aboutApp': 'ऐप के बारे में',
    'userID': 'यूजर आईडी',
    'userPassword': 'यूजर पासवर्ड',
    'working_district_name': 'कार्यरत अधिकारी के जनपद का नाम',
    'inspection_district_name': 'निरीक्षण जनपद का नाम',
    'officer_name': 'अधिकारी का नाम',
    'officer_subName': 'अधिकारी का पदनाम',
    'officer_mobileNumber': 'अधिकारी का मोबाइल नंबर',
    'four_digit_otp_number_darj_karin': 'चार अंकों का ओटीपी नंबर दर्ज करें',
    'date_and_time': 'दिनांक और समय',
    "about_app_desc1":
        """This App has been operationalised by Technosys Services Pvt. Ltd. (www.technosysservices.com).\n
      Technosys Services is a premier organisation by IIT Kanpur, IIT Bombay and IIT Roorkee alumni.\n
      Technosys Services works on cutting edge Cloud Computing Framworks and Platforms and expertise in managing large and very large scale sophisticated
Information Technology and Information and Communication Technology framworks and platforms.""",
    'select_location': 'लोकेशन का चयन करें',
    'start_inspection_with_verified_location':
        'सत्यापित लोकेशन के साथ निरीक्षण करें',
    'start_inspection_with_current_location':
        'वर्तमान लोकेशन के साथ निरीक्षण करें',
    'reportSee': 'रिपोर्ट देखें',
    'institutionAboutUs': 'संस्थान के बारे में',
    'locationWithVerified': 'लोकेशन का सत्यापन करें',
    'withoutLocationWithVerified': 'बिना लोकेशन सत्यापन के आगे बढ़ें',
    'passwordSee': 'पासवर्ड बदलें',
    'aboutUsForApp':
        'समाज कल्याण विभाग द्वारा संचालित संस्थानों यथा जयप्रकाश नारायण सर्वोदय विद्यालयों , वृद्धाश्रमों , छात्रावासों , इत्यादि के निरीक्षण में सहयोग के उद्देश्य से समाज कल्याण निरीक्षण ऐप का संचालन किया जा रहा है।',
    'currentOtpNumber': 'ओटीपी कोड गलत है कृपया सही टिप दर्ज करें।',
    'location': 'लोकेशन',
    'savedDataOnServer': 'अपना बचा डेटा सुरक्षित करना चाहते है?',
    'doYouWantExitApp': 'आप ऐप से बाहर निकलना चाहते हैं?',
    'dataSavedServer': 'आपका डेटा सर्वर पर सुरक्षित है',
    'dataNotSavedServer': 'आपका डेटा सर्वर पर सुरक्षित नहीं है',
    'alreadySavedDataOnServer':
        'आपका डेटा पहले से ही सर्वर पर सुरक्षित हो चूका है',
    'commentHere': 'टिप्पणी लिखें',
    'yourAppNotUpdated': 'आपका ऐप अपडेट नहीं है. कृपया अपडेट करें.',
    "vridha_ashram_name": "वृद्धाश्रम का नाम",
    "hostel_name": "छात्रावास का नाम",
    "dataNotAvailable": "डेटा उपलब्ध नहीं है",
    "school_inspection_report_new": "विद्यालय निरीक्षण रिपोर्ट",
    "hostel_inspection_report_new": "छात्रावास निरीक्षण रिपोर्ट",
    "vridha_ashram_inspection_report_new": "वृद्धाश्रम निरीक्षण रिपोर्ट",
    "inspection_report": "निरीक्षण रिपोर्ट",
    'institutionNameAndAddress': 'संस्था का नाम',
    "vridhaAshram": "वृद्धाश्रम",
    'otpSentClick': 'ओ.टी.पी. भेजें',
    'nextForQuestionnaire': 'आगे बढ़ें',
    'previousForQuestionnaire': 'पीछे जाएँ',
    'thisFeatureIsComingSoon': 'यह सुविधा जल्द ही उपलब्ध होगी',
    'saveAsDropOut': 'सेव करें',
    'preview': 'प्रीव्यू देखें ',
    'cancel': 'रद्द करें',
    'comment': 'टिप्पणी',
    'ratedMarks': 'मूल्यांकित अंक',
    "totalityStudentWithPresent":
        "विद्यालय में पंजीकृत छात्र/छात्राओं की संख्या कुल छात्र की क्षमता से अधिक है",
    "presentStudentWithAbsent":
        "विद्यालय में उपस्थित छात्र/छात्राओं की संख्या पंजीकृत छात्र/छात्राओं की संख्या से अधिक है",
    'adoOfficeInspection': 'एडीओ कार्यालय \n निरीक्षण',
    'adoOfficeInspectionReport': 'एडीओ कार्यालय निरीक्षण \n रिपोर्ट',
    "adoOfficeName": "एडीओ कार्यालय का नाम",
    "adoOfficeInspectionToolbar": "एडीओ कार्यालय निरीक्षण",
    'adoOfficeInspectionReport': 'एडीओ कार्यालय\nनिरीक्षण रिपोर्ट देखें',
    'adoOfficeInspectionReportNew': 'एडीओ कार्यालय निरीक्षण रिपोर्ट',
    "dswOfficeInspectionToolbar": "समाज कल्याण विभाग\nकार्यालय निरीक्षण",
    "abhyudayInspectionToolbar": "अभ्युदय कोचिंग सेंटर निरीक्षण",

    "dswOfficeInspectionReportToolbar": "समाज कल्याण विभाग कार्यालय निरीक्षण",
    "dswOfficeInspectionReportName": "समाज कल्याण विभाग कार्यालय का नाम",
    "dswOfficeInspectionReport": "समाज कल्याण विभाग\nकार्यालय निरीक्षण रिपोर्ट",
    "abhyudayInspectionReport": "अभ्युदय कोचिंग\nसेंटर निरीक्षण रिपोर्ट",
    "dswOfficeInspectionReportNew": "समाज कल्याण विभाग कार्यालय निरीक्षण रिपोर्ट",

    "totalityVARegisterAndAccepted": "वृद्धावस्था पेंशन योजना में स्वीकृत की संख्या कुल आवेदन की संख्या से अधिक है",
    "totalityVAAcceptedAndNotAccepted": "वृद्धावस्था पेंशन योजना में अस्वीकृत की संख्या स्वीकृत की संख्या से अधिक है",
    "abhyudayName": "अभ्युदय कोचिंग सेंटर का नाम",
    "abhyudayInspectionReportToolbar": "अभ्युदय कोचिंग सेंटर निरीक्षण रिपोर्ट",
  };

  static final Map<String, String> _hindiStrings = {
    'title': 'मेरा ऐप',
    'welcome_message': 'मेरे ऐप में आपका स्वागत है!',
    'next': 'क्लिक करें',
    "please_enter_four_digit_otp": "कृपया चार अंकों का ओटीपी दर्ज करें",
    "enter_confirm_pin_here": "दोबारा पिन दर्ज करें..",
    "please_create_four_digit_pin": "कृपया चार अंकों का पिन बनाएं!",
    "create_pin": "पिन बनाएं",
    "registration_with_mobile_number": "मोबाइल नंबर के साथ पंजीकरण",
    "enter_mobile_number_here": "मोबाइल नंबर दर्ज करें...",
    "enter_password_here": "पासवर्ड दर्ज करें...",
    "login": "लॉग इन करें",
    "inspection": "निरीक्षण करें",
    "report": "निरीक्षण रिपोर्ट देखें",
    "leave": "छुट्टी",
    "samajkalyan_inspection": "समाज कल्याण निरीक्षण",
    "school_inspection": "विद्यालय\nनिरीक्षण",
    "hostel_inspection": "छात्रावास\nनिरीक्षण",
    "vridha_ashram_inspection": "वृद्धाश्रम\nनिरीक्षण",
    "samajkalyan_inspection_report": "समाज कल्याण निरीक्षण रिपोर्ट",
    "school_inspection_report": "विद्यालय निरीक्षण\nरिपोर्ट देखें ",
    "hostel_inspection_report": "छात्रावास निरीक्षण\nरिपोर्ट देखें ",
    "vridha_ashram_inspection_report": "वृद्धाश्रम निरीक्षण\nरिपोर्ट देखें ",
    "please_enter_correct_pin": "कृपया सही पिन दर्ज करें|",
    "please_wait": "कृपया प्रतीक्षा करें...",
    "master_screen_hint":
        "कृप्या ऐप को ऑफलाइन उपयोग करने के लिए डेटा को डाउनलोड करने तक प्रतीक्षा करें।",
    "database_name": 'Samajkalyan.db',
    "something_went_to_wrong_please_try_again":
        "कुछ ग़लत पाया गया है। कृपाया पुन: प्रयास करें!!",
    "yes": "हाँ",
    "no": "नहीं",
    "inspection_dashBoard": "निरीक्षण",
    "school_name": "विद्यालय का नाम",
    "school_udisecode": "यू-डायस कोड",
    "school_inspection_toolbar": "विद्यालय निरीक्षण",
    "school_inspection_report_toolbar": "निरीक्षण रिपोर्ट",
    "hostel_inspection_toolbar": "छात्रावास निरीक्षण",
    "vridha_ashram_inspection_toolbar": "वृद्धाश्रम निरीक्षण",
    "please_click_only_three_image": "कृपया आप केवल तीन फोटो क्लिक करें|",
    "please_click_three_image": "कृपया तीन फोटो क्लिक करें|",
    "data_not_found": "डेटा नहीं मिला...",
    "image_uploaded_successfully": "आपका फोटो सफलतापूर्वक अपलोड हो गया है|",
    "no_internet_connection": "आपका इंटरनेट कनेक्शन उपलब्ध नहीं है|",
    "please_click_single_image": "कृपया एक फोटो क्लिक करें|",
    "you_school_location_is_pending": "आपकी लोकेशन लंबित है|",
    "you_school_location_is_reject": "आपकी लोकेशन अस्वीकृत है|",
    "enter_here": "यहाँ भरे",
    "regular_in-charge_principal": "नियमित/प्रभारी प्रधानाचार्य",
    "regular_spokesperson": "नियमित प्रवक्ता",
    "contract_spokesperson": "संविदा प्रवक्ता",
    "regular_assistant_teacher": "नियमित सहायक अध्यापक",
    "contract_assistant_teacher": "संविदा सहायक अध्यापक",
    "varist_sahayak": "वरिष्ठ सहायक",
    "kanist_sahayak": "कनिष्ठ सहायक",
    "hostel_assistant": "छात्रवास सहायक",
    "formist": "फार्मासिस्ट",
    "computer_operator": "कंप्यूटर ऑपरेटर",
    "niyamit_chaturath_sherri_karmchari": "नियमित चतुर्थ श्रेणी कर्मचारी",
    "contract_chaturath_sherri_karmchari": "संविदा चतुर्थ श्रेणी कर्मचारी",
    "outsourcing_chaturath_sherri_karmchari":
        "आउटसोर्सिंग चतुर्थ श्रेणी कर्मचारी",
    "surachha_gaurd_home_gaurd_prd": "सुरक्षा गार्ड (होम गार्ड/पी0आर0डी)",
    "regular_cleaning_staff": "नियमित सफाई कर्मचारी",
    "outsourcing_cleaning_staff": "आउटसोर्सिंग सफाई कर्मचारी",
    "total": " कुल",
    "vidayalay_ki_kul_chhatr_chhamta_kitani_hai":
        "विद्यालय की कुल छात्र क्षमता कितनी है |",
    "vidayalay_me_kul_panjikrit_chhaaatr/chhaatrao_ki_number":
        "विद्यालय में पंजीकृत छात्र/छात्राओं की संख्या",
    "vidayalay_me_kul_upasthit_chhaaatr/chhaatrao_ki_number":
        "विद्यालय में उपस्थित छात्र/छात्राओं की संख्या",
    "vidhayalay_me_karyarat_shaicharick_karmcharyo_ki_number_ke_sambhan":
        "विद्यालय में कार्यरत शैक्षणिक कर्मचारियों की संख्या के संबंध में-",
    "serial_no": "क्रमांक",
    "name_of_staff": "कर्मचारी का नाम",
    "from_date": "दिनांक से",
    "to_date": "दिनांक तक",
    "applied_for_leave": "छुट्टी का अवेदान हुआ",
    "accept": "स्वीकृत",
    "reject": "अस्वीकृत",
    "forward": "प्रेषित करे",
    "type_of_holiday": "छुट्टी का प्रकार",
    "save": "सबमिट करें",
    "mandal_and_district": "मण्डल एवं जिले का चयन करें",
    'data_saved_successfully': "आपका डाटा सफलतापूर्वक सेव हो गया है|",
    "please_select_mandal": "कृपया मण्डल चुनें",
    'please_select_district': "कृपया जिला चुनें",
    "mandal": "मण्डल",
    'district': "जिला",
    'select': "--चुनें--",
    'school_data_saved_successfully':
        'विद्यालय का डाटा सफलतापूर्वक सेव हो गया है|',
    'dashBoard': 'डैशबोर्ड',
    'switchUser': 'यूजर बदलें',
    'schoolListUpdate': 'विद्यालय लिस्ट अपडेट करें',
    'questionnairesListUpdate': 'प्रश्नावली अपडेट करें',
    'reportUpdate': 'रिपोर्ट अपडेट करें',
    'aboutApp': 'ऐप के बारे में',
    'userID': 'यूजर आईडी',
    'userPassword': 'यूजर पासवर्ड',
    'working_district_name': 'कार्यरत जनपद का नाम',
    'inspection_district_name': 'निरीक्षण जनपद का नाम',
    'officer_name': 'अधिकारी का नाम',
    'officer_subName': 'अधिकारी का पदनाम',
    'officer_mobileNumber': 'अधिकारी का मोबाइल नंबर',
    'four_digit_otp_number_darj_karin': 'चार अंकों का ओटीपी नंबर दर्ज करें',
    'date_and_time': 'दिनांक और समय',
    "about_app_desc1":
        """This App has been operationalised by Technosys Services Pvt. Ltd. (www.technosysservices.com).\n
      Technosys Services is a premier organisation by IIT Kanpur, IIT Bombay and IIT Roorkee alumni.\n
      Technosys Services works on cutting edge Cloud Computing Framworks and Platforms and expertise in managing large and very large scale sophisticated
Information Technology and Information and Communication Technology framworks and platforms.""",

    'select_location': 'लोकेशन का चयन करें',
    'start_inspection_with_verified_location':
        'सत्यापित लोकेशन के साथ निरीक्षण करें',
    'start_inspection_with_current_location':
        'वर्तमान लोकेशन के साथ निरीक्षण करें',
    'reportSee': 'रिपोर्ट देखें',
    'institutionAboutUs': 'संस्थान के बारे में',
    'locationWithVerified': 'लोकेशन का सत्यापन करें',
    'withoutLocationWithVerified': 'बिना लोकेशन सत्यापन के आगे बढ़ें',
    'passwordSee': 'पासवर्ड बदलें',
    'aboutUsForApp':
        'समाज कल्याण विभाग द्वारा संचालित संस्थानों यथा जयप्रकाश नारायण सर्वोदय विद्यालयों , वृद्धाश्रमों , छात्रावासों , इत्यादि के निरीक्षण में सहयोग के उद्देश्य से समाज कल्याण निरीक्षण ऐप का संचालन किया जा रहा है।',
    'currentOtpNumber': 'ओटीपी कोड गलत है कृपया सही टिप दर्ज करें।',
    'location': 'लोकेशन',
    'savedDataOnServer': 'अपना बचा डेटा सुरक्षित करना चाहते है?',
    'doYouWantExitApp': 'आप ऐप से बाहर निकलना चाहते हैं?',
    'dataSavedServer': 'आपका डेटा सर्वर पर सुरक्षित है',
    'dataNotSavedServer': 'आपका डेटा सर्वर पर सुरक्षित नहीं है',
    'alreadySavedDataOnServer':
        'आपका डेटा पहले से ही सर्वर पर सुरक्षित हो चूका है',
    'commentHere': 'टिप्पणी लिखें',
    'yourAppNotUpdated': 'आपका ऐप अपडेट नहीं है. कृपया अपडेट करें.',
    "vridha_ashram_name": "वृद्धाश्रम का नाम",
    "hostel_name": "छात्रावास का नाम",
    "dataNotAvailable": "डेटा उपलब्ध नहीं है",
    "school_inspection_report_new": "विद्यालय निरीक्षण रिपोर्ट",
    "hostel_inspection_report_new": "छात्रावास निरीक्षण रिपोर्ट",
    "vridha_ashram_inspection_report_new": "वृद्धाश्रम निरीक्षण रिपोर्ट",
    "inspection_report": "निरीक्षण रिपोर्ट",
    'institutionNameAndAddress': 'संस्था का नाम',
    "vridhaAshram": "वृद्धाश्रम",
    'otpSentClick': 'ओ.टी.पी. भेजें',
    'nextForQuestionnaire': 'आगे बढ़ें',
    'previousForQuestionnaire': 'पीछे जाएँ',
    'thisFeatureIsComingSoon': 'यह सुविधा जल्द ही उपलब्ध होगी',
    'saveAsDropOut': 'सेव करें',
    'preview': 'प्रीव्यू देखें ',
    'cancel': 'रद्द करें',
    'comment': 'टिप्पणी',
    'ratedMarks': 'मूल्यांकित अंक',
    "totalityStudentWithPresent":
        "विद्यालय में पंजीकृत छात्र/छात्राओं की संख्या कुल छात्र की क्षमता से अधिक है",
    "presentStudentWithAbsent":
        "विद्यालय में उपस्थित छात्र/छात्राओं की संख्या पंजीकृत छात्र/छात्राओं की संख्या से अधिक है",
    'adoOfficeInspection': 'एडीओ कार्यालय \n निरीक्षण',
    'adoOfficeInspectionReport': 'एडीओ कार्यालय\nनिरीक्षण रिपोर्ट देखें',
    "adoOfficeName": "एडीओ कार्यालय का नाम",
    'adoOfficeInspectionReportNew': 'एडीओ कार्यालय निरीक्षण रिपोर्ट',
    "adoOfficeInspectionToolbar": "एडीओ कार्यालय निरीक्षण",

    "dswOfficeInspection": "समाज कल्याण विभाग\nकार्यालय निरीक्षण",
    "abhyudayInspection": "अभ्युदय कोचिंग\nसेंटर निरीक्षण",

    "dswOfficeInspectionReport": "समाज कल्याण विभाग\nकार्यालय निरीक्षण रिपोर्ट",
    "abhyudayInspectionReport": "अभ्युदय कोचिंग\nसेंटर निरीक्षण रिपोर्ट",
    "dswOfficeInspectionReportNew": "समाज कल्याण विभाग कार्यालय निरीक्षण रिपोर्ट",
    "dswOfficeInspectionReportToolbar": "समाज कल्याण विभाग कार्यालय निरीक्षण",
    "dswOfficeInspectionReportName": "समाज कल्याण विभाग कार्यालय का नाम",

    "totalityVARegisterAndAccepted": "वृद्धावस्था पेंशन योजना में स्वीकृत की संख्या कुल आवेदन की संख्या से अधिक है",
    "totalityVAAcceptedAndNotAccepted": "वृद्धावस्था पेंशन योजना में अस्वीकृत की संख्या स्वीकृत की संख्या से अधिक है",
    "enter_pin_here": "पिन दर्ज करें..",
    "abhyudayInspectionToolbar": "अभ्युदय कोचिंग सेंटर निरीक्षण",
    "abhyudayName": "अभ्युदय कोचिंग सेंटर का नाम",
    "abhyudayInspectionReportToolbar": "अभ्युदय कोचिंग सेंटर निरीक्षण रिपोर्ट",
  };

  static String? getString(String key, {String locale = 'hi'}) {
    if (locale == 'hi' && _hindiStrings.containsKey(key)) {
      return _hindiStrings[key];
    } else {
      return _englishStrings[key];
    }
  }
}
