// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6aK_C-tEt1nr3LUK23WTPyeDpG_JbNHg',
    appId: '1:175240813690:web:26f4f72f410623a10d6fc3',
    messagingSenderId: '175240813690',
    projectId: 'ambulancepassengerapp',
    authDomain: 'ambulancepassengerapp.firebaseapp.com',
    storageBucket: 'ambulancepassengerapp.firebasestorage.app',
    measurementId: 'G-MS4XV96LEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVuj92XN-ZGbBGqUY9izENzFdsBFV4lr0',
    appId: '1:175240813690:android:68189a481be99be20d6fc3',
    messagingSenderId: '175240813690',
    projectId: 'ambulancepassengerapp',
    storageBucket: 'ambulancepassengerapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-gZMA8PJImX2_KmOgoWLuuKu0-DVwv-8',
    appId: '1:175240813690:ios:97d5412ff734e79b0d6fc3',
    messagingSenderId: '175240813690',
    projectId: 'ambulancepassengerapp',
    storageBucket: 'ambulancepassengerapp.firebasestorage.app',
    iosBundleId: 'com.example.flnteachertraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-gZMA8PJImX2_KmOgoWLuuKu0-DVwv-8',
    appId: '1:175240813690:ios:97d5412ff734e79b0d6fc3',
    messagingSenderId: '175240813690',
    projectId: 'ambulancepassengerapp',
    storageBucket: 'ambulancepassengerapp.firebasestorage.app',
    iosBundleId: 'com.example.flnteachertraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6aK_C-tEt1nr3LUK23WTPyeDpG_JbNHg',
    appId: '1:175240813690:web:a3a6fe92e21db3240d6fc3',
    messagingSenderId: '175240813690',
    projectId: 'ambulancepassengerapp',
    authDomain: 'ambulancepassengerapp.firebaseapp.com',
    storageBucket: 'ambulancepassengerapp.firebasestorage.app',
    measurementId: 'G-DYB00M8GFK',
  );

}