class AppStrings {
  static final Map<String, String> _hindiStrings = {
    'aboutUsForApp':
        'समाज कल्याण विभाग द्वारा संचालित संस्थानों यथा जयप्रकाश नारायण सर्वोदय विद्यालयों , छात्रावासों , इत्यादि के निरीक्षण में सहयोग के उद्देश्य से Physical Progress Samajkalyan App का संचालन किया जा रहा है।',
    "about_app_desc1":
        """This App has been operationalised by Technosys Services Pvt. Ltd. (www.technosysservices.com).\n
      Technosys Services is a premier organisation by IIT Kanpur, IIT Bombay and IIT Roorkee alumni.\n
      Technosys Services works on cutting edge Cloud Computing Framworks and Platforms and expertise in managing large and very large scale sophisticated
Information Technology and Information and Communication Technology framworks and platforms.""",

    'baseUrl': 'http://atmsapi.technosysservicesdemos.com/apiurl/getapiurl',
    'baseUrlTest': 'http://www.aatms.com/apiurl/getapiurl',
    'title': 'मेरा ऐप',
    'welcome_message': 'मेरे ऐप में आपका स्वागत है!',
    'userPassword': 'पिन डालें',
    'click': 'क्लिक करें',
    "please_enter_four_digit_otp": "कृपया चार अंकों का ओटीपी दर्ज करें",
    "enter_confirm_pin_here": "दोबारा पिन दर्ज करें..",
    "please_create_four_digit_pin": "कृपया चार अंकों का पिन बनाएं!",
    "create_pin": "पिन बनाएं",
    "registration_with_mobile_number": "मोबाइल नंबर के साथ पंजीकरण",
    "enter_mobile_number_here": "मोबाइल नंबर दर्ज करें...",
    "enter_password_here": "पासवर्ड दर्ज करें...",
    "login": "लॉग इन करें",
    'registerYourMobileNumber': 'अपना मोबाइल नंबर रजिस्टर करें',
    'enterNumber': 'नंबर दर्ज करें',
    'please_wait': 'कृपया प्रतीक्षा करें',
    'next': 'आगे बढ़ें',
    'bashBoard': 'डैशबोर्ड',
    'doYouWantExitApp': 'आप ऐप से बाहर निकलना चाहते हैं?',
    'switchUser': 'यूजर बदलें',
    'reportSee': 'रिपोर्ट देखें',
    'aboutApp': 'ऐप के बारे में',
    'userID': 'यूजर आईडी',
    'institutionAboutUs': 'संस्थान के बारे में',
    'locationWithVerified': 'लोकेशन का सत्यापन करें',
    'withoutLocationWithVerified': 'बिना लोकेशन सत्यापन के आगे बढ़ें',
    'passwordSee': 'पासवर्ड बदलें',
    'attendanceReport': 'उपस्थिति रिपोर्ट',
    'no': 'नहीं',
    'yes': 'हाँ',
    'yourAppNotUpdated': 'आपका ऐप अपडेट नहीं है. कृपया अपडेट करें.',
    'personDetails': 'व्यक्ति की जानकारी',
    'personDetailsReport': 'व्यक्ति की रिपोर्ट',
    'designation': 'पद',
    'mobileNumber': 'मोबाइल नंबर ',
    'dataNotAvailable': 'डाटा उपलब्ध नहीं है',
    'data_saved_successfully': "आपका डाटा सफलतापूर्वक सेव हो गया है|",
    'dataNotSavedServer': 'आपका डेटा सर्वर पर सुरक्षित नहीं है',
    'profile': 'प्रोफाइल',
    'profileReport': 'प्रोफाइल रिपोर्ट',
    'refreshPersonDetails': 'डाटा रिफ्रेश करें',
    "something_went_to_wrong_please_try_again":
        "कुछ ग़लत पाया गया है। कृपाया पुन: प्रयास करें!!",
    'dataSavedSuccessfully': "आपका डाटा सफलतापूर्वक सेव हो गया है|",
    'dataNotSavedSuccessfully': "आपका डाटा सेव नहीं हुआ है|",
    'faceCapture': "फेस कैप्चर",
    'faceCaptureReport': "फेस कैप्चर रिपोर्ट",
    'savedDataOnServer': 'शेष डेटा सुरक्षित करना चाहते है?',
    'alreadySavedDataOnServer':
        'आपका डेटा पहले से ही सर्वर पर सुरक्षित हो चूका है',
    'attendanceAbsentPresent': "अनुपस्थिति /उपस्थिति ",
    'dateTime': "तारीख /समय",
    'dailyReport': "दिनांकवार रिपोर्ट",
    'monthlyReport': "माहवार रिपोर्ट",
    'attendanceReportDashboard': "उपस्थिति रिपोर्ट",
    'dailyReportToolBar': "दिनांकवार उपस्थिति रिपोर्ट",
    'geoMap': 'मैप',
    'location': 'लोकेशन',
    'update': 'अपडेट',
    'updateSavedSuccessfully': 'डाटा सफलतापूर्वक अपडेट हो गया है|',
    'scanQRCode': 'स्कैन QR कोड',
    'Allocated': 'आवंटित सुविधाएं',
    'inspection': 'निरीक्षण ',
    'inspectionReport': 'निरीक्षण  रिपोर्ट',
    'Save': 'सुरक्षित',
    'image_uploaded_successfully': 'फोटो सफलतापूर्वक अपलोड हो गया है|',
    "enter_pin_here": "पिन बनाएं...",
    "no_internet_connection": "No Internet Connection",
    "facilityType": "सुविधा प्रकार",
    "tantNames": "टेंट का नाम",
    "description": "विवरण",
    "profile_creation_data": "प्रोफ़ाइल विवरण डाटा",
    "please_wait_your_data_is_loading":
        "कृपया सभी डेटा डाउनलोड होने तक इंतजार करे तथा डेटा डाउनलोड होने के बाद ही आगे बढ़ें",
    "attendance_data": "उपस्थिति डाटा",
    'voter_management_system': 'वोटर मैनेजमेंट सिस्टम system',
    'dashboard': 'डैशबोर्ड',
    'manage_team_manager': 'टीम मेनेजर',
    'view_edit_team_manager': 'देखें /संपादित करें',
    'add_team_manager': 'टीम मेनेजर जोड़ें',
    'assign_task_to_manager': 'भाग से संबद्ध करें',
    'manage_team_member': 'टीम सदस्य ',
    'view_edit_team_member': 'देखें /संपादित करे',
    'add_team_member': 'टीम सदस्य जोड़ें ',
    'assign_task_to_member': 'सेक्शन से संबद्ध करें',
    'analytics': 'विश्लेषण',
    'families_surveyed': 'सर्वेक्षण किये गए परिवार',
    'search_electors': 'मतदाता खोजें',
    'team_manager_registration': 'टीम मेनेजर की जानकारी जोड़ें',
    'name': 'नाम',
    'father': 'पिता',
    'husbanName': 'पति का नाम',
    'mobileNo': 'मोबाइल न.',
    'alternetMobile': 'वैकल्पिक मोबाइल न.',
    'dob': 'जन्म तिथि',
    'age': 'आयु  (वर्ष में )',
    'yearOfJoining': 'पार्टी से जुड़ने का वर्ष ',
    'totalYears_ofServing': 'सेवा की अवधि( वर्ष  में )',
    'address': 'पता ',
    'pinCode': 'पिनकोड',
    'save': 'सुरक्षित करें ',
    'team_Manager_Deatails': 'टीम मेनेजर की जानकारी देखें /संपादित करें ',
    'father_and_husbandName': 'Father/husband Name',
    'action': 'कार्यवाही',
    'view': 'देखें',
    'edit': 'संपादित करें ',
    'team_manager_task_assign_report': 'भाग से संबद्ध करें ',
    'sr_no': 'Sr.no.',
    'team_manager': 'टीम मेनेजर',
    'part_both_count': 'संबद्ध किये गए भागों की संख्या ',
    'part_both_name': 'संबद्ध किये गए भागों के नाम ',
    'asignTask': 'संबद्ध करें ',
    'team_manager_task_asign_report1':
        'पहले से संबद्ध किये जा चुके /रिक्त भागों का विवरण ',
    'already_assigned_manager': 'पहले से संबद्ध मेनेजर ',
    'assign_not_assign_to': '<नाम> कों संबद्ध करें /हटायें  ',
    'assembly_Constitunency': 'विधानसभा क्षेत्र ',
    'part': 'भाग ',
    'section': 'अनुभाग',
    'houseNo': 'मकान न. ',
    'sr_no_in_part': 'भाग में क्र.सं. ',
    'id_no': 'आई.डी . न. ',
    'search': 'खोजें ',
    'family_elector': 'परिवार /मतदाता सत्यापन ',
    'members': 'सदस्य का नाम ',
    'survey_completed': 'सर्वेक्षण किया गया ',
    'families': 'परिवार',
    'electors': 'मतदाता',
    'verified_survey': 'सत्यापित सर्वेक्षण',
    'survey_pending_for_verification': 'सत्यापन के लिए लंबित सर्वेक्षण',
    'maintain_family': 'परिवार ',
    'add_Family': 'जोड़ें ',
    'maintain_voters': 'परिवार जोड़ें ',
    'important_point': 'महत्वपूर्ण बिंदु ',
    'individuals': 'Individuals',
    'add_new_voter': 'नया मतदाता जोड़ें ',
    'individual_survey': 'व्यक्तिगत सर्वेक्षण ',
    'religion': 'धर्म',
    'category': 'वर्ग ',
    'caste': 'जाति ',
    'sub_caste': 'उप-जाति ',
    'traditional_voter': 'परंपरागत मतदाता ',
    'likelyhood_of_voting': 'मतदान की संभावना ',
    'conversion_exoectancy_level': 'आय वर्ग ',
    'income_group': 'आय वर्ग',
    'influence_status': 'प्रभाव स्थिति ',
    'information_provided_by': 'दी गई जानकारी',
    'majra': 'मजरा ',
    'associatedorg': "संबंधित संगठन",
    'ac': "ऐ.सी. ",
    'associated_with_family': 'परिवार से जुड़ा हुआ ',
    'not_associated_with_family': 'परिवार से ना जुड़ा हुआ ',
    'associatedwithselectedfamily': 'चयनित परिवार से जुड़ा हुआ',
    'relationname': 'संबंधी का नाम',
    'email': 'ईमेल',
    'district': 'जिला',
    'area': "क्षेत्र का प्रकार",
    'block': 'ब्लॉक',
    'town': 'शहर',
    'ward': 'वार्ड',
    'panchayat': 'पंचायत',

    "start_date": "Start Date",
    "please_click_only_three_image": "Please Click Only Three Image.",
    //
    "sarvodya_school_progress_app": "Sarvodya School Progress App",
    "economical_physical_progress": "Economical Physical\nProgress",

    "Session_2024_25": "Session: 2024-25",
    "school_name": "विद्यालय का नाम",
    "school_udise_code": "विद्यालय यूनाईस कोड",
    "update_school_data": "Update School Data",
    "enter_mobile_number": "मोबाइल नंबर",
    "data_not_found": "Data Not Found",

    "pointer_name": "सूचक का नाम",
    "financial_year": 'वित्तीय वर्ष',
    "amount_allocated": 'आवंटित धनराशि',
    'previous_physical_progress': 'पिछली भौतिक प्रगति',
    'last_amount_spent': 'पिछली उपभोग की गई धनराशि',
    'previous_balance': 'पिछली शेष धनराशि',
    'consumption_amount': 'उपभोग धनराशि',
    'enter_consumption_amount': 'उपभोग धनराशि भरें',
    'remaining_amount': 'शेष धनराशि',
    'material_progress': 'भौतिक प्रगति',

    'state_of_saturation': 'संतृप्तिकरण की स्थिति',
    'saturated': 'संतृप्त',
    'unsaturated': 'असंतृप्त',
    'status': 'स्थिति',
    'select_task_status': 'कार्य स्थिति चुनें',
    'comment': 'टिप्पणी',
    "submit": 'submit',
    "upload_document": 'अपलोड दस्तावेज़',
    'take_photo': "फोटो लो",
    'please_enter_consumption_amount': 'कृपया उपभोग धनराशि भरें',
    'please_material_progress': 'कृपया भौतिक प्रगति भरें',
    'please_state_of_saturation': 'कृपया संतृप्तिकरण की स्थिति चुनना',
    'please_comment': 'कृपया टिप्पणी भरें',
    'please_select_task_status': 'कृपया कार्य स्थिति चुनें',
    "economical_physical_progress_report":
        "Economical Physical\nProgress Report",
    // New App ForSchools management System
    'attendance': 'उपस्थिति',
    'AlreadyRegister':'Already Register,Please Login!',
    'resetting_password':'Resetting password, please wait...'
  };
  static final Map<String, String> _englishStrings = {
    'aboutUsForApp':
        'समाज कल्याण विभाग द्वारा संचालित संस्थानों यथा जयप्रकाश नारायण सर्वोदय विद्यालयों , छात्रावासों , इत्यादि के निरीक्षण में सहयोग के उद्देश्य से Physical Progress Samajkalyan App का संचालन किया जा रहा है।',
    "about_app_desc1":
        """This App has been operationalised by Technosys Services Pvt. Ltd. (www.technosysservices.com).\n
      Technosys Services is a premier organisation by IIT Kanpur, IIT Bombay and IIT Roorkee alumni.\n
      Technosys Services works on cutting edge Cloud Computing Framworks and Platforms and expertise in managing large and very large scale sophisticated
      Information Technology and Information and Communication Technology framworks and platforms.""",

    'baseUrlTest': 'http://www.aatms.com/apiurl/getapiurl',
    'baseUrl': 'http://atmsapi.technosysservicesdemos.com/apiurl/getapiurl',


    'title': 'मेरा ऐप',
    'welcome_message': 'मेरे ऐप में आपका स्वागत है!',
    'userPassword': 'पिन डालें',
    'click': 'क्लिक करें',
    "please_enter_four_digit_otp": "कृपया चार अंकों का ओटीपी दर्ज करें",
    "enter_confirm_pin_here": "दोबारा पिन दर्ज करें..",
    "please_create_four_digit_pin": "कृपया चार अंकों का पिन बनाएं!",
    "create_pin": "पिन बनाएं",
    "registration_with_mobile_number": "मोबाइल नंबर के साथ पंजीकरण",
    "enter_mobile_number_here": "मोबाइल नंबर दर्ज करें...",
    "enter_password_here": "पासवर्ड दर्ज करें...",
    "login": "लॉग इन करें",
    'registerYourMobileNumber': 'अपना मोबाइल नंबर रजिस्टर करें',
    'enterNumber': 'नंबर दर्ज करें',
    'please_wait': 'Please Wait',
    'bashBoard': 'Dashboard',
    'doYouWantExitApp': 'आप ऐप से बाहर निकलना चाहते हैं?',
    'switchUser': 'यूजर बदलें',
    'reportSee': 'रिपोर्ट देखें',
    'aboutApp': 'ऐप के बारे में',
    'userID': 'यूजर आईडी',
    'institutionAboutUs': 'संस्थान के बारे में',
    'locationWithVerified': 'लोकेशन का सत्यापन करें',
    'withoutLocationWithVerified': 'बिना लोकेशन सत्यापन के आगे बढ़ें',
    'passwordSee': 'पासवर्ड बदलें',

    'no': 'No',
    'yes': 'Yes',
    'yourAppNotUpdated': 'आपका ऐप अपडेट नहीं है. कृपया अपडेट करें.',
    'personDetails': 'Person Details',
    'personDetailsReport': 'Person Details Report',
    'name': 'Name',
    'designation': 'Designation',
    'mobileNumber': 'Mobile No',
    'dataNotAvailable': 'Data Not Available',
    'data_saved_successfully': "आपका डाटा सफलतापूर्वक सेव हो गया है|",
    'dataNotSavedServer': 'आपका डेटा सर्वर पर सुरक्षित नहीं है',
    'refreshPersonDetails': 'Refresh Person Details',
    'profile': 'Profile',
    'profileReport': 'Profile Report',
    "something_went_to_wrong_please_try_again":
        "कुछ ग़लत पाया गया है। कृपाया पुन: प्रयास करें!!",
    'dataSavedSuccessfully': "आपका डाटा सफलतापूर्वक सेव हो गया है|",
    'dataNotSavedSuccessfully': "आपका डाटा सेव नहीं howa है|",
    'faceCapture': "Face Capture",
    'faceCaptureReport': "Face Capture Report",
    'savedDataOnServer': 'शेष डेटा सुरक्षित करना चाहते है?',
    'alreadySavedDataOnServer':
        'आपका डेटा पहले से ही सर्वर पर सुरक्षित हो चूका है',
    'attendanceAbsentPresent': "Absent/Present",
    'dateTime': "Date/Time",
    'dailyReport': "Daily Report",
    'monthlyReport': "Monthly Report",
    'attendanceReportDashboard': "Attendance Report",

    'geoMap': 'Map',
    'location': 'Location',
    'update': 'Update',
    'updateSavedSuccessfully': 'Update Saved Successfully',

    'scanQRCode': 'Scan QR Code',
    'Allocated': 'Allocated Facilitated',
    'inspection': 'Inspection',
    'inspectionReport': 'Inspection Report',
    'Save': 'Save',
    'image_uploaded_successfully': 'Image Uploaded Successfully',
    "enter_pin_here": "पिन बनाएं...",
    "no_internet_connection": "No Internet Connection",
    "facilityType": "सुविधा प्रकार",
    "tantNames": "टेंट का नाम",
    "description": "विवरण",
    "profile_creation_data": "प्रोफ़ाइल विवरण डाटा",
    "please_wait_your_data_is_loading":
        "कृपया सभी डेटा डाउनलोड होने तक इंतजार करे तथा डेटा डाउनलोड होने के बाद ही आगे बढ़ें",
    "attendance_data": "उपस्थिति डाटा",
    'next': 'आगे बढ़ें',
    'voter_management_system': 'Voter management system',
    'dashboard': 'Dashboard',
    'manage_team_manager': 'Manage Team Manager',
    'view_edit_team_manager': 'View/Edit Team Manager',
    'add_team_manager': 'Add Team Manager',
    'assign_task_to_manager': 'Assign Task To Manager',
    'manage_team_member': 'Manage Team Member',
    'view_edit_team_member': 'View/Edit Team Member',
    'add_team_member': 'Add Team Member',
    'assign_task_to_member': 'Assign Task To Member',
    'analytics': 'Analytics',
    'families_surveyed': 'Families Surveyed',
    'search_electors': 'Search Electors',
    'team_manager_registration': 'Team Manager Registration',
    'father': 'Father',
    'husbanName': 'Husband Name',
    'mobileNo': 'Mobile No.',
    'alternetMobile': 'Alternet Mobile No',
    'dob': 'DOB',
    'age': 'Age (In Year)',
    'yearOfJoining': 'Year Of Joining',
    'totalYears_ofServing': 'Total Years of Serving',
    'address': 'Address',
    'district': 'District',
    'pinCode': 'Pincode',
    'save': 'Save',
    'team_Manager_Deatails': 'Team Manager Details',
    'father_and_husbandName': 'Father/husband Name',
    'action': 'Action',
    'view': 'View',
    'edit': 'Edit',
    'team_manager_task_assign_report': 'Team Manager Task Assign Report',
    'team_manager_task_asign_report1': 'team manager task assign report ',
    'sr_no': 'Sr.no.',
    'team_manager': 'Team Manager',
    'part_both_count': 'Part/Booth Count',
    'part_both_name': 'Part/Booth Name',
    'asignTask': 'AsignTask',
    'already_assigned_manager': 'Already assigned manager',
    'assign_not_assign_to': 'Assign/not assign to',
    'assembly_Constitunency': 'Assembly Constituency',
    'sr_no_in_part': 'Sr.No in part',
    'id_no': 'id no.',
    'search': 'search',
    'family_elector': 'family/electors verification',
    'members': 'Members',
    'section': 'section',
    'survey_completed': 'survey completed',
    'families': 'families',
    'electors': 'electors',
    'verified_survey': 'verified survey',
    'survey_pending_for_verification': 'survey pending for verification',
    'maintain_family': 'Maintain family',
    'add_Family': 'Add Family',
    'maintain_voters': 'Maintain Voters',
    'important_point': 'Important Point',
    'individuals': 'Individuals',
    'add_new_voter': 'Add new voter',
    'individual_survey': 'Individual Survey',
    'religion': 'Religion',
    'category': 'Category',
    'caste': 'caste',
    'sub_caste': 'sub caste',
    'traditional_voter': 'Traditional voter',
    'likelyhood_of_voting': 'Likelyhood of voting',
    'conversion_exoectancy_level': 'Conversion Expectancy Level',
    'income_group': 'Income Group',
    'influence_status': 'Influence Status',
    'information_provided_by': 'Information provided by',
    'majra': 'Majra',
    'associatedorg': "संबंधित संगठन",
    'ac': "AC",
    'part': 'Part',
    'houseNo': 'HouseNo',
    'associated_with_family': 'Associated with family',
    'not_associated_with_family': 'Not Associated with famiy',
    'associatedwithselectedfamily': 'Associated With Selected Family',
    'relationname': 'Relation name',
    'email': 'E-mail',
    'area': "Area Type",
    'block': 'Block',
    'town': 'Town',
    'ward': 'Ward',
    'panchayat': 'Panchayat',

    "start_date": "Start Date",
    "end_date": "End Date",
    "please_click_only_three_image": "Please Click Only Three Image.",

    //
    "sarvodya_school_progress_app": "Sarvodya School Progress App",
    "economical_physical_progress": "Economical Physical\nProgress",
    "school_name": "School Name",
    "school_udise_code": "School UDISE Code",
    "update_school_data": "Update School Data",
    "enter_mobile_number": "मोबाइल नंबर",
    "data_not_found": "Data Not Found",

    "pointer_name": "सूचक का नाम",
    "financial_year": 'वित्तीय वर्ष',
    "amount_allocated": 'आवंटित धनराशि',
    'previous_physical_progress': 'पिछली भौतिक प्रगति',
    'last_amount_spent': 'पिछली उपभोग की गई धनराशि',
    'previous_balance': 'पिछली शेष धनराशि',
    'consumption_amount': 'उपभोग धनराशि',
    'enter_consumption_amount': 'उपभोग धनराशि भरें',
    'remaining_amount': 'शेष धनराशि',
    'material_progress': 'भौतिक प्रगति',

    'state_of_saturation': 'संतृप्तिकरण की स्थिति',
    'saturated': 'संतृप्त',
    'unsaturated': 'असंतृप्त',
    'status': 'स्थिति',
    'select_task_status': 'कार्य स्थिति चुनें',
    'comment': 'टिप्पणी',
    "submit": 'submit',
    "upload_document": 'अपलोड दस्तावेज़',
    'take_photo': "फोटो लो",

    'please_enter_consumption_amount': 'कृपया उपभोग धनराशि भरें',
    'please_material_progress': 'कृपया भौतिक प्रगति भरें',
    'please_state_of_saturation': 'कृपया संतृप्तिकरण की स्थिति चुनना',
    'please_comment': 'कृपया टिप्पणी भरें',
    'please_select_task_status': 'कृपया कार्य स्थिति चुनें',

    "economical_physical_progress_report":
        "Economical Physical\nProgress Report",

    // New For School Management System...

    'attendance': 'Attendance',
    'attendanceReport': 'Attendance Report',
    'achievements': 'achievements',

    'memberType': 'Member Type',
    'contact': 'Contact',
    'issuedBook': 'Issued Book',
    'remainBook': 'Remain Book',
    'overDue': 'Over Due',

    'bookTitle': 'Book Title',
    'ISBN': 'ISBN',
    'subject': 'Subject',
    'publisher': 'Publisher',
    'author': 'Author',
    'language': 'Language',

    'AlreadyRegister':'Already Register,Please Login!',
    'resetting_password':'Resetting password, please wait...'

  };

  static String? getString(String key, {String locale = 'eng'}) {
    if (locale == 'hi' && _hindiStrings.containsKey(key)) {
      return _hindiStrings[key];
    } else {
      return _englishStrings[key];
    }
  }
}
